version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@39
      MYSQL_DATABASE: cms
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cms-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@39
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: your_jwt_secret_key_here
      APP_JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cms-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  cms-network:
    driver: bridge 